### ISSUE TITLE
【実装】レーダーチャート生成

### ISSUE THREAD

**Issue by ShinoharaTa** [428lab/debug-shrine#10]
【メモ】
- 言語推定方法
userのアクティビティfeedを取ってきて(例: https://api.github.com/users/kojira/events )、commits のpayloadのurl(https://api.github.com/repos/kojira/korosuke/commits/2c528494fcd88fc16d0bac5b9e90092a19e56402 )からfilesの数だけcontents_url(例: https://api.github.com/repos/kojira/korosuke/contents/bot.py?ref=2c528494fcd88fc16d0bac5b9e90092a19e56402 )で対応言語の拡張子か確認し(画像ファイルなどは無視)、rangeリクエストで1024byte程度取得し、sizeの項目の値を正規表現で取得し、ファイルサイズを調べる。
※全部取らないのはcontent部分にbase64でファイルが全て含まれているため、サイズが大きい場合にパフォーマンス低下するのを防ぐため。
ファイルサイズだけ取得して、拡張子だけで言語を推定する。
ファイルサイズが小さすぎる(512byte未満)場合は無視する。

不正防止のため、パフォーマンスが低下しない程度(3KB程度？)にraw_urlの実体の途中まで取得して、言語推定モジュールで言語推定するべきかも。

- Guesslangモジュール
https://pythonawesome.com/detect-the-programming-language-of-a-source-code-in-python/

**Comment by kojira** [comment]
初期は言語推定はしない。

**Comment by kojira** [comment]
計算と生成処理自体は完了。
