### ISSUE TITLE
WEBサイト設計

### ISSUE THREAD

**Issue by ShinoharaTa** [428lab/debug-shrine#12]
- ページ一覧
- ページ遷移設計
- 各ページ内部の機能設計
- URL決定

**Comment by a-zenryoku** [comment]
ページ一覧
1：サインイン
2：神社（withおみくじ）
3：マイページ

**Comment by ShinoharaTa** [comment]
想定でコード上に用意したページは以下の通りになります

- トップ（ログインも兼ねつつ）
- マイページ
- おみくじを引くページ（参拝と共通）
- 免責事項
- プライバシーポリシー
- 利用規約

コード上にloginがありますが、今の所使用予定なし。

その他、希望としてページ遷移などの設計がいただければと。
不足していると思われるところは以下の通りです

- 各ユーザーごとのプロフィールページ
- 名刺ページ
- おみくじ結果（公開情報）を表示するためのページ

**Comment by a-zenryoku** [comment]
[Webサイト設計.pptx](https://github.com/428lab/debug-shrine/files/7698001/Web.pptx)
でぃすこへ先に上げちゃいましたが、設計書です。違和感や無理っぽいとこあったらご遠慮なくご相談のほど。

**Comment by a-zenryoku** [comment]
しまった。SNSシェアが抜けてた。

**Comment by ShinoharaTa** [comment]
SNSシェアはユーザーのページとおみくじ結果のページですかね

**Comment by a-zenryoku** [comment]
[Webサイト設計v2.pptx](https://github.com/428lab/debug-shrine/files/7698147/Web.v2.pptx)
更新版こちらです

**Comment by a-zenryoku** [comment]
@ShinoharaTa 
概ねそうですね。ユーザーの公開ページに最新の結果を載せておく感じで良いかと。

**Comment by penginnu** [comment]
Webサイト設計v2 ベースで実装進め始めますね

**Comment by penginnu** [comment]
ルーティング案

/              トップ
/resister  初回登録
/dashboard マイページ
/settings  プロフィール
/omikuji   参拝
/u/_userName  マイオフィシャル
/privacy-policy   プライバシーポリシー
/terms            利用規約

**Comment by kojira** [comment]
/about
を追加。
これにてclose
