### ISSUE TITLE
利用規約など文章系作成

### ISSUE THREAD

**Issue by penginnu** [428lab/debug-shrine#19]
・利用規約の作成
・プライバシーポリシーの作成
・免責事項の作成（利用規約内でもいいかも）

**Comment by penginnu** [comment]
[プライバシーポリシー草案](https://github.com/428lab/debug-shrine/wiki/Draft-Privacy-Policy)

**Comment by penginnu** [comment]
[免責事項草案](https://github.com/428lab/debug-shrine/wiki/Draft-Disclaimer)

**Comment by penginnu** [comment]
[利用規約草案](https://github.com/428lab/debug-shrine/wiki/Draft-Terms-of-service)

**Comment by ShinoharaTa** [comment]
草案作成ありがとう！
