### ISSUE TITLE
サービス説明文検討

### ISSUE THREAD

**Issue by ShinoharaTa** [428lab/debug-shrine#2]

**Comment by yamashin0922** [comment]
【由緒】

今は昔、南のはずれに漁師の村があったそうな。
数年の不漁続きで、村の食べ物も底をついておった。

ある嵐の夜、沖で難破してる外国の船を見つけたんじゃ。
漁師たちは、嵐の中に小舟を出して懸命に救助を試みたのじゃが、
海は大しけで、助けることができたのはたった一人の若い男じゃった。
船団長の娘が手厚く世話をしたおかげで、男は一命をとりとめたそうな。

男はめっぽう腕の立つ機関士で、「助けて頂いたお礼がしたい」と、回復した後も漁村にとどまり、
舟や家の修理はもちろん、沈没船から道具や機材を引き上げ、便利なモノを次々とこしらえおった。
中でも、真空管っちゅう機械を使って、なんでも計算できる、とんでもない箱を創ってしもたんじゃ。
その噂は、村から町へ、町から都へと広がり、男の創った箱や技術は大変重宝され、次々と広まったんじゃ。

噂が殿様の耳に入るのは、そう時間がかからなかったそうな。
殿様はめっぽう将棋が強く、勝負する相手がおらんほどじゃった。


/*　検討中　*/



その真空管に、その男の名を取って「Lord・Hawar（ロード・ハワール）」と名付け、
今でもインターネットのどこかに、そのご神体をまつった神社があるという。

**Comment by kojira** [comment]
close
