### ISSUE TITLE
おみくじ内容の校正

### ISSUE THREAD

**Issue by yamashin0922** [428lab/debug-shrine#20]

**Comment by yamashin0922** [comment]
・「死」や死を連想させる言葉の使用を制限
・助言、予言等になるよう、言い回しを校正
・AWS・Slackなどのサービス名を一般名詞に置き換え
・言霊の追加
・言霊を「助言」「予言」「ボケ」に分類
・レイアウトを考慮して、改行コードを明示的に追加

**Comment by yamashin0922** [comment]
最初の１０８の言霊をcsvファイルとしてアップしました。残りも頑張る。
857adfbeea8c750f950b05025833ba09641d6f21

**Comment by yamashin0922** [comment]
全おみくじ文章の校正を完了。
e61de6459e5088f416ba995738d0ee9aacc9b940

**Comment by kojira** [comment]
close
