### ISSUE TITLE
PC向け画面のレイアウトがでかすぎる

### ISSUE THREAD

**Issue by kojira** [428lab/debug-shrine#26]
何もかもがデカい。
無駄に縦スクロールしないといけない。
![image](https://user-images.githubusercontent.com/428875/147496439-392a2bc1-5c4a-4557-93c4-3c1c3aff50d4.png)
![image](https://user-images.githubusercontent.com/428875/147496594-6fcc8688-50b2-4539-a2a7-822cd4a6ba41.png)

**Comment by ShinoharaTa** [comment]
開発段階で、スマホ向けに最適化した状態から作っています。
この先、レスポンシブにPCレイアウトへ対応していく予定

**Comment by kojira** [comment]
PCでトップページ、マイページの縦スクロールが不要になるなら問題ないです。

**Comment by ShinoharaTa** [comment]
対応済み
