### ISSUE TITLE
でばっぐ神社の神様の名前検討

### ISSUE THREAD

**Issue by ShinoharaTa** [428lab/debug-shrine#3]

**Comment by yamashin0922** [comment]
デバッグとはバグを取り除くこと、バグの由来は諸説あるが、真空管に虫（バグ）が入って装置の不具合をあらわす隠語として技術者の間で使われたことが始まり。
ご神体は「古びた真空管」にしたい。
神様の名前は真空管にちなんだ名前、できれば和名が良い。

**Comment by yamashin0922** [comment]
真之空電神（まことのそらいかづち）
真空電神（まことのそらいかづち）
真空大神（まことのそらのおおかみ）
真空之電神（まことのそらいかづち）
真空之大神（まことのそらのおおかみ）
真空ノ電神（まことのそらいかづち）
真空ノ大神（まことのそらのおおかみ）
真ノ空ノ電神（まことのそらいかづち）
真ノ空ノ大神（まことのそらのおおかみ）
真之空之電神（まことのそらいかづち）
真之空之大神（まことのそらのおおかみ）

**Comment by yamashin0922** [comment]
「Lord・Hawar（ロード・ハワール）」
#2

**Comment by kojira** [comment]
露御読把和流(ろおどはわる)
になりました。
