### ISSUE TITLE
ビルドの自動化

### ISSUE THREAD

**Issue by zinntikumugai** [428lab/debug-shrine#35]
```
env/dev
env/stg
env/prod
```
各ブランチで対応したやつにでぷろい

**Comment by zinntikumugai** [comment]
https://github.com/428lab/debug-shrine/commit/ff2afa09e6570b7131a1078d1d19033275ebc2ca `env/dev` OK

**Comment by zinntikumugai** [comment]
https://github.com/428lab/debug-shrine/commit/e46b028bcab7d3f83fd969e7c6f952d98a53b87c `env/prod` 対応
functions configはdevを引き継ぎ

**Comment by zinntikumugai** [comment]
ステージングのぷろじぇくとisどこよ

**Comment by ShinoharaTa** [comment]
ステージングのプロジェクトは無し。
完了とします。
