### ISSUE TITLE
ユーザーが存在しなくてもユーザー情報が表示される

### ISSUE THREAD

**Issue by kojira** [428lab/debug-shrine#38]
https://d-shrine-dev.web.app/u/aaaaaaa などのページを表示してもT.Shinoharaの情報が表示されてしまう。

**Comment by ShinoharaTa** [comment]
まだ仮データ対応中。

ユーザー情報を取得し、あったら表示、ないときは404対応
なお、該当ユーザーない時はresponseのステータスコードは404にて。

**Comment by ShinoharaTa** [comment]
@kojira 

未登録のユーザーの場合は404？

**Comment by kojira** [comment]
404で。

**Comment by zinntikumugai** [comment]
https://github.com/428lab/debug-shrine/commit/cc230a7f6c66ecf422073a8544e8d296abc0add0 API`/status`は 対応済み

**Comment by zinntikumugai** [comment]
https://github.com/428lab/debug-shrine/commit/ffd80e6d9116e5f578161bb84b9ff5d067de7594 OGP対応

**Comment by ShinoharaTa** [comment]
ページの実装は404対応済み
