### ISSUE TITLE
参拝しても文言がでない

### ISSUE THREAD

**Issue by kojira** [428lab/debug-shrine#41]
![image](https://user-images.githubusercontent.com/428875/147742061-2af5fc8c-07ac-4ced-8e15-46ef8689b9c5.png)
この画面が出るだけで文言がでない。

**Comment by zinntikumugai** [comment]
https://github.com/428lab/debug-shrine/commit/462151e55d11866db2e4df3930ed653b1279e956
https://github.com/428lab/debug-shrine/commit/483758d175be26a8d40b15636031f293ba3c7506
対応済み
