### ISSUE TITLE
トップページに行くと毎回OAuthが必要

### ISSUE THREAD

**Issue by kojira** [428lab/debug-shrine#42]
マイページに行くとログインされているのに、「GitHubと連携してログイン」を押すと毎回OAuth処理が入る。
期待結果：
ログインされている時は「参拝する」になっているべき。

**Comment by zinntikumugai** [comment]
https://github.com/428lab/debug-shrine/commit/a57c9d9bcf820f78777e0466afa40ec69288ff87
https://github.com/428lab/debug-shrine/commit/de1496b837607fd033d6a7b41ce5c26e88c97747
修正
