### ISSUE TITLE
OGイメージが表示されない

### ISSUE THREAD

**Issue by kojira** [428lab/debug-shrine#43]
トップページとユーザーページのOGイメージが設定されていない。

**Comment by zinntikumugai** [comment]
トップページは仮で対応

静的サイトなのでユーザーページはfunctionsで頑張る

**Comment by zinntikumugai** [comment]
hostingにrewrite
functionsで受け取って、ビルド時に生成した`index.html`をstorageに置いておいて、それを書き換えたものを返す?

**Comment by zinntikumugai** [comment]
参考
- [Nuxt.js + FirebaseのSPAで動的にOGPを生成することのあれこれ](https://qiita.com/kanoi_y/items/c71a967673ce7944409d)
- [SNS映えするWebアプリを...！FirebaseとVue.jsでSPAのOGP画像の動的生成をやってみたら案外楽だった](https://qiita.com/yuneco/items/5e526464939082862f5d)

**Comment by zinntikumugai** [comment]
https://github.com/428lab/debug-shrine/commit/155bb3c18a675b56a309fb9b9c9947b7210bf302
でけた
