### ISSUE TITLE
OGPに載せる情報

### ISSUE THREAD

**Issue by zinntikumugai** [428lab/debug-shrine#48]
- ページタイトル
- サイト名
- ディスクリプション

の文言、フォーマット

- トップページ
  - タイトル：``
  - サイト名：`でばっく神社`
  - ディスクリプション：``

- ユーザーページ
  - タイトル：``
  - サイト名：`でばっく神社`
  - ディスクリプション：`これが${username}の でばっぐのうりょくだ！`

**Comment by kojira** [comment]
完了。
