### ISSUE TITLE
エラーが出て参拝できない

### ISSUE THREAD

**Issue by KASHIHARAAkira** [428lab/debug-shrine#51]
同じアカウント（本アカウント）でログインし、参拝した後、ダッシュボードへアクセスするとエラーが発生して参拝結果が見られない。
macOS 12.0.1のFirefox（95.0.2 (64 ビット)）で「エラーが発生しました　500」、Chrome（96.0.4664.110（Official Build） （x86_64））で「このページは存在しません404」が出る（ブラウザによってエラーコードが違うのが不思議）。
以下が、それぞれのブラウザのコンソール表示結果。

## Firefox
```
ソースマップエラー: Error: NetworkError when attempting to fetch resource.
リソース URL: moz-extension://0b670de4-c7d5-6f4e-845f-837beee6ed5c/common/browser-polyfill.js
ソースマップ URL: browser-polyfill.js.map
```

## Chrome
```
Failed to load resource: the server responded with a status of 404 ()
Uncaught (in promise) Error: Request failed with status code 404
    at t.exports (5279600.js:2)
    at t.exports (5279600.js:2)
    at XMLHttpRequest.A (5279600.js:2)
DevTools failed to load source map: Could not load content for chrome-extension://cmhflcgkckeenbbcgoilnnbbbejmpiae/common/browser-polyfill.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
```

**Comment by kojira** [comment]
@KASHIHARAAkira 
OGP関連の変更でバグっていたようです。
直近のリリースで直ってる…はずです！
お暇な時に試してみてください。

**Comment by KASHIHARAAkira** [comment]
一度、Githubのapplicationsの連携を切って、再度ログインすると、参拝することが出来ました。

**Comment by KASHIHARAAkira** [comment]
> @KASHIHARAAkira OGP関連の変更でバグっていたようです。 直近のリリースで直ってる…はずです！ お暇な時に試してみてください。

できました、早速の対応、ありがとうございます！

**Comment by kojira** [comment]
リリースとタイミングが重なったみたいですね！
Closeいたします。
