### ISSUE TITLE
フロントエンドのTypeScript化, typed-vuexの導入

### ISSUE THREAD

**Issue by MaySoMusician** [428lab/debug-shrine#52]
- 保守性向上のためのTypeScript化
- またTS化して[typed-vuex](https://github.com/danielroe/typed-vuex)を導入することで、Vuexへのアクセスにインテリセンスを効かせることができるようになります

実装例: [Vuex部分](https://github.com/MaySoMusician/geidai-ikoi/blob/bae59d25d82e1758352b949abc744919871e49fb/store/index.ts), [使用例（ログイン処理など）](https://github.com/MaySoMusician/geidai-ikoi/blob/bae59d25d82e1758352b949abc744919871e49fb/pages/index.vue#L137-L545)

**Comment by ShinoharaTa** [comment]
Nuxt 2系のサポート終了が近いため、フレームワークを変更予定
そのためこのままクローズします
