### ISSUE TITLE
【仕様策定】デバッグあるあるツイート

### ISSUE THREAD

**Issue by ShinoharaTa** [428lab/debug-shrine#8]
広報、運用方法などを考える。

**Comment by kojira** [comment]
428labのTwitterアカウントで元となるネタをハッシュタグ付きでツイートし、でばっぐ神社開発者でもツイートしていく。
ハッシュタグは
```
#デバッグあるある #でばっぐ神社
```
関係者はでばっぐ神社のurlも付ける。
